name: pipeline-ci

on:
  push:
    branches:
      -  feature-*

jobs:
  SAST:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Configuration
        run: |
          sonarcloud_create_project=$(curl -s -u '${{ secrets.SONAR_TOKEN }}:' '${{ secrets.SONAR_HOST_URL }}/api/projects/create' \
          -d 'name=${{ github.event.repository.name }}' \
          -d 'project=${{ github.event.repository.name }}' \
          -d 'organization=${{ github.repository_owner }}' \
          -d 'visibility=public' \
          -w "\n%{http_code}")
          sonarcloud_create_project_status=$(tail -n1 <<< "$sonarcloud_create_project") 
          sonarcloud_create_project_response=$(sed '$ d' <<< "$sonarcloud_create_project")
          if [ $sonarcloud_create_project_status -eq 200 ]; then
            echo "Proyecto ${{ github.event.repository.name }} creado exitosamente en Sonarcloud"
            echo "Se establece rama main como rama por defecto"
            curl -s -u '${{ secrets.SONAR_TOKEN }}:' '${{ secrets.SONAR_HOST_URL }}/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
          else
            error_msg = $(echo "$sonarcloud_create_project_response" | jq .errors[].msg | sed -e 's/^"//' -e 's/"$//')
            if [[ "$error_msg" == Could not create Project, key already exists: ${{ github.event.repository.name }}" ]]; then
              echo "Proyecto ya existe en Sonarcloud"
            else
              echo "::error title=API_ERROR::$error_msg"
            fi
          fi

      - name: Install dependencies
        run: npm install

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=${{ github.repository_owner }}
            -Dsonar.projectKey=${{ github.event.repository.name }}
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}